DigitalGlobe/pyveda

pyveda/training.py
adding property methods for a datapoint's bounds and tile coords
=> property for bounds and tile coords

pyveda/__init__.py, pyveda/models.py, pyveda/training.py
Updating the use of `data` in datapoints and VedaCollections. The API is moving to GeoJSON features for all outputs, this will support that.
=> supporting geojson from the server

pyveda/training.py
change to make VedaCollection easier to explore
=> changing items in kwargs to explicitly be in init method

pyveda/fetch/aiohttp/client.py, pyveda/main.py, pyveda/vedaset/store/vedabase.py, pyveda/vedaset/stream/vedastream.py
Fixes context managers
Fixes off-by-one error in vedabase
=> Consolidate store

pyveda/main.py
replace `dataset_exists` with `from_id` and `from_name`
=> replace `dataset_exists` with `from_id` and `from_name`

pyveda/utils.py, pyveda/veda/api.py
When working with VedaCollectionProxy we want to be able to add samples to a collection. This involves adding a method that will accept and RDA Image (via gbdxtools) and a label that matches the given type needed for the mltype of the collection. On the API side the handler for POSTs to `/data/datasetID/datapoints` accepts an image and metadata needed to create the new sample. It uploads the image to s3 and adds the sample to the DB. 
Calling add_sample requires a couple things. For sake of simplicity the below code adds a sample to a classification collection: 
```python
import pyveda as pv
from pyveda.veda.rda import MLImage
collection = pv.from_id('67a16de1-7baf-44bf-a779-2bf97a37c3bd')
img = MLImage('1030010059998700', pansharpen=False)
aoi = img.randwindow((256,256))
label = …
```
=> support for add_sample on VedaCollectionProxy

tests/unit/test_main.py
initial tests for `main.py` function
=> Consolidate tests martha

pyveda/frameworks/batch_generator.py, pyveda/vedaset/store/vedabase.py, pyveda/vedaset/stream/vedastream.py
Add `VedaStream` Generator class
=> VedaStream Generator 

pyveda/frameworks/batch_generator.py
This PR fixes the shape returned for object detection y data for the basic batch generator without augmentations.
=> Fix object detection generator y data shape

pyveda/frameworks/batch_generator.py
change so channels last is now implemented correctly so batches with `channels_last=True` have shape: 
`32, 256, 256, 3`
=> channels last change to make work

pyveda/frameworks/transforms.py
change `flip_vertical` and `flip_horizontal` transform functions to support multi-class object detection
=> fix multi-class od transforms

pyveda/veda/api.py, pyveda/vv/labelizer.py
This branch makes clean work with a vcp by calling vcp.clean()
=> Labelizer vcp

pyveda/frameworks/batch_generator.py, pyveda/frameworks/transforms.py
generator now returns correct output for all classes for multi-class object detection 
augmentation also works with multi-class object detection 
object detection horizontal and vertical flip functions changed to be more efficient and use list comprehension
=> Fixes for object detection multi-class

pyveda/main.py
=> add create_from_tarball as practice

pyveda/main.py
Reverts DigitalGlobe/pyveda#54
=> Revert "add create_from_tarball as practice"

pyveda/veda/api.py, pyveda/vv/labelizer.py
This fix improves color balancing for uint16 images in .preview() and .clean().
=> Mlt 191 labelizer color fixes

pyveda/veda/rda.py
Change MLImage to inherit from RDABaseImage and add an MLImage driver. This persists the options when slicing/subsetting.
=> MlImage refactor for slicing

pyveda/frameworks/batch_generator.py
What does this PR do?
---------------------
- custom y label transform was previously only applied to the VedaBase generator, now it is also added to the VedaStream generator. Allows for users to input a custom function that will transform y labels.
:white_check_mark: Checklist
---------------------
- [ X] No additional work is in process. This PR should be ready for merge right now.
- [X ] There is at least one assignee
=> MLT-236 fix 

pyveda/veda/api.py
What does this PR do?
---------------------
- Companion to https://github.com/DigitalGlobe/veda/pull/20
- Sends class lists as JSON to avoid problems when class names have commas in them
What steps, if any, do reviewers need to take to set up their environments to test this properly?
---------------------
- Need to have https://github.com/DigitalGlobe/veda/pull/20 in your local codebase
- Can test with e77ddb1c-cbae-4192-98cf-3a9563349011, it has commas in the class names
Acceptance criteria
---------------------
- datapoint labels shouldn't change
Known issues
---------------------
- Needs https://github.com/DigitalGlobe/veda/pull/20 fix applied to API first
- tests are limited on this side too, need something like:
```python
vc = pv.from_id('e77ddb1c-cbae-4192-98cf-3a9563349011')
for x …
```
=> Send class list as JSON

.gitignore, .travis.yml, Makefile, pyveda/vedaset/base.py, pyveda/vedaset/veda/api.py, pyveda/vedaset/veda/props.py, tests/unit/test_api.py, tests/unit/test_main.py, tests/unit/test_vedabase.py, tests/unit/test_vedacollection.py, tests/unit/test_vedahandlers.py
What does this PR do?
---------------------
- Updates unit tests to be compatible with current api
- Changes VCP.imshape to a tuple type in order to match the behavior of numpy's `.shape`
What steps, if any, do reviewers need to take to set up their environments to test this properly?
---------------------
- Pull the changes and `make test`
Acceptance criteria
---------------------
- Tests pass
Known issues
---------------------
- Many of the tests already had commented out code.  I left much of that in, as I'm not sure whether commented code corresponds to test code that should be removed or test code that should be updated to match the present api
- Test coverage is still not good
:white_check_mark: Checklist
---------------------
Attn @msmith303
=> pyveda unit tests

README.md, pyveda/io/hdf5/serializers.py, setup.py
What does this PR do?
---------------------
Updates README, import bug fix, removes conditional py2 install logic in setuptools, bumps version 0.0.5 -> 0.0.6 in setuptools.
-
What steps, if any, do reviewers need to take to set up their environments to test this properly?
---------------------
None
-
Acceptance criteria
---------------------
None
-
Known issues
---------------------
None
-
:white_check_mark: Checklist
---------------------
Attn @msmith303
=> Prep releases
